In [16]:
import pandas as pd
import numpy as np

#read dataset
df=pd.read_csv("Jill_August_1_shortened.csv")         
df.head()

,Product Name,Available Quantity,Color,Size,Size Name,Price,Sale Price,Price Type,Date,Location,ID,Variant ID,SKU
0,PIMA ANKLE LEGGINGS,457,white,L,Misses,39.0,39.0,full price,2021-08-01,3J006B,801,408638,220991801L
1,PIMA ANKLE LEGGINGS,321,white,M,Misses,39.0,39.0,full price,2021-08-01,3J006B,801,408639,220991801M
2,PIMA ANKLE LEGGINGS,259,white,S,Misses,39.0,39.0,full price,2021-08-01,3J006B,801,408640,220991801S
3,PIMA ANKLE LEGGINGS,139,white,XL,Misses,39.0,39.0,full price,2021-08-01,3J006B,801,408641,220991801XL
4,PIMA ANKLE LEGGINGS,132,white,XS,Misses,39.0,39.0,full price,2021-08-01,3J006B,801,408642,220991801XS

In [18]:
#change variable types
df.dtypes
#df['Price Type']=df['Price Type'].astype('category')
#df['Price Type']=df['Price Type'].cat.codes
#df['productName']=df['Product Name']
df['priceType']=df['Price Type']
df.head()

,Product Name,Available Quantity,Color,Size,Size Name,Price,Sale Price,Price Type,Date,Location,ID,Variant ID,SKU,productName,priceType
0,PIMA ANKLE LEGGINGS,457,white,L,Misses,39.0,39.0,full price,2021-08-01,3J006B,801,408638,220991801L,PIMA ANKLE LEGGINGS,full price
1,PIMA ANKLE LEGGINGS,321,white,M,Misses,39.0,39.0,full price,2021-08-01,3J006B,801,408639,220991801M,PIMA ANKLE LEGGINGS,full price
2,PIMA ANKLE LEGGINGS,259,white,S,Misses,39.0,39.0,full price,2021-08-01,3J006B,801,408640,220991801S,PIMA ANKLE LEGGINGS,full price
3,PIMA ANKLE LEGGINGS,139,white,XL,Misses,39.0,39.0,full price,2021-08-01,3J006B,801,408641,220991801XL,PIMA ANKLE LEGGINGS,full price
4,PIMA ANKLE LEGGINGS,132,white,XS,Misses,39.0,39.0,full price,2021-08-01,3J006B,801,408642,220991801XS,PIMA ANKLE LEGGINGS,full price

In [23]:
#drop unnecessary columns
df1=df.drop('Product Name',axis=1,inplace=True)

#separate target from dependent variables
target=df.priceType
inputs=df.drop('priceType',axis=1)

In [24]:
#change variable type
size=pd.get_dummies(inputs.productName)

In [25]:
inputs=pd.concat([inputs,size],axis=1)
inputs.drop('productName',axis=1,inplace=True)
inputs.head()

,3/4-SLEEVE BOAT-NECK KNIT TOP,4 WAY STRETCH HIGH-RISE SKINNY JEANS,A-LINE SWEATER DRESS,A-LINE SWEATER TUNIC,AF EMBELLISHED-HEM ANKLE JEANS,ARBOR V-NECK SWEATER,AUTHENTIC FIT BUTTONED-HEM ANKLE JEANS,AUTHENTIC FIT FRINGED-HEM CROPPED JEANS,AUTHENTIC FIT SLIM LEG,AUTHENTIC FIT SLIM-LEG JEANS,...,WEAREVER FULL-LEG SHORTS,WEAREVER LAYERING TANK,WEAREVER MIXED-STRIPES DUSTER,WEAREVER PERFECT V-NECK TEE,WEAREVER PLEATED-NECKLINE TUNIC,WEAREVER RIBBED BOAT-NECK DRESS,WEAREVER SAFARI JACKET,WEAREVER SEAMED BOAT-NECK TOP,WEAREVER SHIRTTAIL-HEMLINE TOP,WEAREVER V-NECK A-LINE DRESS
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [26]:
#split dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(inputs,target,test_size=0.2)

In [27]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()

In [28]:
#train model
model.fit(X_train,y_train)

GaussianNB()

In [29]:
model.score(X_test,y_test)

0.8005148005148005

In [34]:
X_test[:10]

,3/4-SLEEVE BOAT-NECK KNIT TOP,4 WAY STRETCH HIGH-RISE SKINNY JEANS,A-LINE SWEATER DRESS,A-LINE SWEATER TUNIC,AF EMBELLISHED-HEM ANKLE JEANS,ARBOR V-NECK SWEATER,AUTHENTIC FIT BUTTONED-HEM ANKLE JEANS,AUTHENTIC FIT FRINGED-HEM CROPPED JEANS,AUTHENTIC FIT SLIM LEG,AUTHENTIC FIT SLIM-LEG JEANS,...,WEAREVER FULL-LEG SHORTS,WEAREVER LAYERING TANK,WEAREVER MIXED-STRIPES DUSTER,WEAREVER PERFECT V-NECK TEE,WEAREVER PLEATED-NECKLINE TUNIC,WEAREVER RIBBED BOAT-NECK DRESS,WEAREVER SAFARI JACKET,WEAREVER SEAMED BOAT-NECK TOP,WEAREVER SHIRTTAIL-HEMLINE TOP,WEAREVER V-NECK A-LINE DRESS
2391,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4470,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2831,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3776,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4385,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7091,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10608,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5695,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5682,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8943,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [31]:
y_test[:10]

2391     full price
4470     full price
2831     full price
3776     full price
4385     full price
7091        on sale
10608       on sale
5695     full price
5682     full price
8943        on sale
Name: priceType, dtype: object

In [32]:
model.predict(X_test[:10])

array(['on sale', 'full price', 'full price', 'full price', 'full price',
       'on sale', 'on sale', 'full price', 'full price', 'on sale'],
      dtype='<U10')

In [33]:
model.predict_proba(X_test[:10])

array([[0.00000000e+000, 1.36866105e-285, 1.00000000e+000],
       [0.00000000e+000, 1.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 1.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 1.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 1.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 1.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 1.00000000e+000],
       [0.00000000e+000, 1.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 1.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 2.12672434e-268, 1.00000000e+000]])

      extendedSize  priceType
24461       Petite          1
24462       Misses          0
24463       Misses          2
24464       Misses          2
24465         Tall          0